### ISSUE TITLE
TeamsTeam: Make Ensure mandatory

### ISSUE THREAD

**Issue by robertreems** [microsoft/Office365DSC#372] opened 2020-02-15 09:27 UTC
#### Details of the scenario you tried and the problem that is occurring
I was creating a new team in my test environment but it never was created as I didn't use the Ensure parameter.

#### Verbose logs showing the problem

Verbose logging without ensure provided

VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Resource ]  [[TeamsTeam]TeamsTeam_MySecondTeam]
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Test     ]  [[TeamsTeam]TeamsTeam_MySecondTeam]
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Testing configuration of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Getting configuration of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Checking for existance of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Teams with displayname MySecondTeam doesn't exist
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Current Values: AllowAddRemoveApps=False; AllowChannelMentions=False; AllowCreateUpdateChannels=False; AllowCreateUpdateRemoveConnectors=Fa
lse; AllowCreateUpdateRemoveTabs=False; AllowCustomMemes=False; AllowDeleteChannels=False; AllowGiphy=False; AllowGuestCreateUpdateChannels=False; AllowGuestDeleteChannels=False; AllowOwnerDeleteMessages=False; AllowStickersAndMe
mes=False; AllowTeamMentions=False; AllowUserDeleteMessages=False; AllowUserEditMessages=False; Description=; DisplayName=MySecondTeam; Ensure=Absent; GiphyContentRating=; GlobalAdminAccount=System.Management.Automation.PSCredent
ial; GroupId=; MailNickName=; Owner=(robert@reems.onmicrosoft.com); Visibility=
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Target Values: DisplayName=MySecondTeam; GlobalAdminAccount=System.Management.Automation.PSCredential; Owner=(robert@reems.onmicrosoft.com)
; Verbose=True
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Test-TargetResource returned True
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Test     ]  [[TeamsTeam]TeamsTeam_MySecondTeam]  in 2.0890 seconds.
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Skip   Set      ]  [[TeamsTeam]TeamsTeam_MySecondTeam]
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Resource ]  [[TeamsTeam]TeamsTeam_MySecondTeam]

Verbose logging with ensure parameter provided.

VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Resource ]  [[TeamsTeam]TeamsTeam_MySecondTeam]
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Test     ]  [[TeamsTeam]TeamsTeam_MySecondTeam]
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Testing configuration of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Getting configuration of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Checking for existance of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Teams with displayname MySecondTeam doesn't exist
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Current Values: AllowAddRemoveApps=False; AllowChannelMentions=False; AllowCreateUpdateChannels=False; AllowCreateUpdateRemoveConnectors=Fa
lse; AllowCreateUpdateRemoveTabs=False; AllowCustomMemes=False; AllowDeleteChannels=False; AllowGiphy=False; AllowGuestCreateUpdateChannels=False; AllowGuestDeleteChannels=False; AllowOwnerDeleteMessages=False; AllowStickersAndMe
mes=False; AllowTeamMentions=False; AllowUserDeleteMessages=False; AllowUserEditMessages=False; Description=; DisplayName=MySecondTeam; Ensure=Absent; GiphyContentRating=; GlobalAdminAccount=System.Management.Automation.PSCredent
ial; GroupId=; MailNickName=; Owner=(robert@reems.onmicrosoft.com); Visibility=
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Target Values: DisplayName=MySecondTeam; Ensure=Present; GlobalAdminAccount=System.Management.Automation.PSCredential; Owner=(robert@reems.
onmicrosoft.com); Verbose=True
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Test-TargetResource returned False
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Test     ]  [[TeamsTeam]TeamsTeam_MySecondTeam]  in 2.8960 seconds.
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ Start  Set      ]  [[TeamsTeam]TeamsTeam_MySecondTeam]
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Setting configuration of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Getting configuration of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Checking for existance of Team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Teams with displayname MySecondTeam doesn't exist
VERBOSE: [RVRAZRO365Dsc1]:                            [[TeamsTeam]TeamsTeam_MySecondTeam] Creating team MySecondTeam
VERBOSE: [RVRAZRO365Dsc1]: LCM:  [ End    Set      ]  [[TeamsTeam]TeamsTeam_MySecondTeam]  in 10.3610 seconds.

#### Suggested solution to the issue
Make ensure mandatory so an error is produced when the parameter is omitted. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

TeamsTeam TeamsTeam_MySecondTeam{
            GlobalAdminAccount = $TenantCredential
            DependsOn = '[O365User]O365User_Robert'
            DisplayName = 'MySecondTeam'
            Owner = 'robert@XXX.onmicrosoft.com'
        }

```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.0.2.1589

**Comment by Markus-Hanisch** [comment] 2020-02-16 13:56
@robertreems I double-checked your Verbose output and went through the [MSFT_TeamsTeam.psm1](https://github.com/microsoft/Office365DSC/blob/Dev/Modules/Office365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1) file. The root cause of your issue seems to be that the function Test-TargetResource defaults to true, because its Ensure parameter is set to `Ensure = "Present"` by default if the Ensure parameter is not specified with another value. Thereby the Set-TargetResource will be skipped because your Team is already present. 

I don't exactly understand the reason why the Ensure parameter is also set to default to `Ensure = "Present"` in the functions Get-TargetResource and Set-TargetResource. 
I only found out in the [readme.md](https://github.com/microsoft/Office365DSC/tree/Dev/Modules/Office365DSC/DSCResources/MSFT_TeamsTeam#parameters) file, header **Parameters** > Ensure that the option Ensure = "Absent" will throw an error. 
However, in the Test-TargetResource function must not have any default as this causes confusion (or requires a mandatory parameter as you requested). Therefore, I removed the fault setting in that function.

**Comment by andikrueger** [comment] 2020-02-20 15:35
There is some more information available within this [article](https://docs.microsoft.com/en-us/powershell/scripting/dsc/resources/resources?view=powershell-7) about the `Ensure` parameter. Ensure defaults to Present as it's an optional parameter.

**Comment by Markus-Hanisch** [comment] 2020-02-21 21:28
@andikrueger 
Thank you for the clarification in here. Okay, so to put it in other words ... the desired behavior is:
IF
Teams Team is not yet present and the _Ensure_ parameter is not specified,
THEN
**Test-TargetResource** will _SKIP SET_ because the **Test** function  it defaults the _Ensure_ parameter to "Present".
I will close my pull request.

**Comment by andikrueger** [comment] 2020-02-21 22:08
Thank you for rephrasing. From my understanding, there is an error within this resource. The `Test-TargetResource` should return false. 
There is no need to set `Ensure` To `Present`. As soon as you specify a resource (with or without `Ensure=“Present”` does not matter) the resource should run `Set-TargetResource` if the desired configuration is not in place yet. 

Your verbose log shows: `Ensure=Absent`, but with having in `Ensure` an optional property that defaults to `“Present”` the `Test-TargetResource` should return `false`.

**Comment by Markus-Hanisch** [comment] 2020-02-22 07:19
@andikrueger 
Going through the logic of `Test-TargetResource` and the Verbose output from @robertreems again, I think I figured out the root cause why the `Test-TargetResource` `$TestResult` returns to `True`.
The `$PSBoundParameters` does only contain parameters that are explicitly set by the caller, but does NOT contain any defaults (source: [$PSBoundParameters](https://ss64.com/ps/psboundparameters.html):
> The automatic variable $PSBoundParameters is a hashtable containing the parameters passed to a script or a function.
It only includes the values of parameters that were explicitly supplied by the caller, so it does not include any which have been left at the default value.

If you compare the Verbose output, you will notice that the _Target Values_ section does not contain the `Ensure` parameter. However, the `$ValuesToCheck` variable is set to `$PSBoundParameters` and does therefore also not contain the `Ensure` parameter. In other words, the `Ensure` parameter is not even checked in the `Test-Office365DSCParameterState` function as it only compares the key-value pairs which are present in `$PSBoundParameters`. Therefore the `$TestResult` returns to `True`.
See [lines 495 -514 in Test-TargetResource](https://github.com/microsoft/Office365DSC/blob/6ce08df7b85782e8c8011d98dc8357fadc3dc01b/Modules/Office365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1#L493-L514)
```powershell
    $CurrentValues = Get-TargetResource @PSBoundParameters

    Write-Verbose -Message "Current Values: $(Convert-O365DscHashtableToString -Hashtable $CurrentValues)"
    Write-Verbose -Message "Target Values: $(Convert-O365DscHashtableToString -Hashtable $PSBoundParameters)"

    $ValuesToCheck = $PSBoundParameters
    $ValuesToCheck.Remove('GlobalAdminAccount') | Out-Null
    $ValuesToCheck.Remove('GroupID') | Out-Null

    if ($null -eq $CurrentValues.Owner)
    {
        $ValuesToCheck.Remove("Owner") | Out-Null
    }

    $TestResult = Test-Office365DSCParameterState -CurrentValues $CurrentValues `
        -Source $($MyInvocation.MyCommand.Source) `
        -DesiredValues $PSBoundParameters `
        -ValuesToCheck $ValuesToCheck.Keys

    Write-Verbose -Message "Test-TargetResource returned $TestResult"

    return $TestResult
```

So what is the conclusion? 
Well, I thought through some possibilities.
I think you will need to add the `Ensure` parameter default to the `$PSBoundParameter`, e.g. **`$PSBoundParameters.Add('Ensure','Present')`**. 
Doing so, the "DesiredValues" will include the `Ensure` parameter. Furthermore, the "ValuesToCheck" will will also check for it:
```powershell
    $CurrentValues = Get-TargetResource @PSBoundParameters
    # Add Ensure paramater default "Present" to $PSBoundParameters
    $PSBoundParameters.Add('Ensure','Present')

    Write-Verbose -Message "Current Values: $(Convert-O365DscHashtableToString -Hashtable $CurrentValues)"
    Write-Verbose -Message "Target Values: $(Convert-O365DscHashtableToString -Hashtable $PSBoundParameters)"

    $ValuesToCheck = $PSBoundParameters
    $ValuesToCheck.Remove('GlobalAdminAccount') | Out-Null
    $ValuesToCheck.Remove('GroupID') | Out-Null

    if ($null -eq $CurrentValues.Owner)
    {
        $ValuesToCheck.Remove("Owner") | Out-Null
    }

    $TestResult = Test-Office365DSCParameterState -CurrentValues $CurrentValues `
        -Source $($MyInvocation.MyCommand.Source) `
        -DesiredValues $PSBoundParameters `
        -ValuesToCheck $ValuesToCheck.Keys

    Write-Verbose -Message "Test-TargetResource returned $TestResult"

    return $TestResult
```
Should I create a PR?

**Comment by andikrueger** [comment] 2020-02-22 07:32
Sounds valid. 

Your code would set `Ensure` to `Present` regardless of the set/bound value. 

The following line should be sufficient to solve this problem:

`$PSBoundParameters.Ensure = $Ensure`

**Comment by Markus-Hanisch** [comment] 2020-02-22 07:47
@andikrueger Yes, I just questioned it myself ;D 
By default the `$PSBoundParameters` won't have an "Ensure" key. Will your code `$PSBoundParameters.Ensure = $Ensure` add the the "Ensure" key automatically to the `$PSBoundParameters` variable or do I need to set it as follows: `$PSBoundParameters.Add('Ensure',$Ensure)`?

**Comment by andikrueger** [comment] 2020-02-22 07:55
Hashtables in PowerShell are not that picky. This is more a question of “style”. You could add a value by either 
- $hashtable.Add(Key, Value)
- $hashtable.Key = Value
- $hashtable[“Key”] = Value

I’d go with option one which is the most obvious.

**Comment by robertreems** [comment] 2020-02-24 06:24
Thank you guys for your research and prompt fix!

**Closed** 2020-03-02 16:37 UTC
Labels: Bug
